apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo_app
  template:
    metadata:
      labels:
        app: mongo_app
    spec:
      containers:
      - name: mongo
        image: mongo:6.0.5
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef: 
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: mongo-secret
              key: mongo-password
      - name: mongo-express
        image: mongo-express:1.0.0-alpha.4
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef: 
              name: mongo-secret
              key: mongo-user
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef: 
              name: mongo-secret
              key: mongo-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef: 
              name: mongo-config
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service-int
spec:
  selector:
    app: mongo_app
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service-ext
spec:
  type: NodePort
  selector:
    app: mongo_app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081